/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.catalyst.expressions.codegen.varka;

import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;

import jdk.incubator.vector.IntVector;
import jdk.incubator.vector.VectorMask;
import jdk.incubator.vector.VectorSpecies;

/**
 * Compaction: turning a batch plus a selection bitmap into a dense batch of just the selected
 * rows (task 24, milestone 4 item 11). The filter node's other half - the kernel that produces
 * the bitmap - is emitted, not written by hand; this is the copy that follows it, and it is
 * hand-written for the same reason the engine's kernels are, as the reference for how the
 * shape composes.
 *
 * <p><b>Why it lives in catalyst rather than beside the engine's kernels.</b> The engine module
 * is a <i>test</i>-scope dependency of both catalyst and {@code sql/core}: production code never
 * links it, and generated bytecode reaches {@code VarkaVectorSupport} by name through the
 * context class loader. This kernel is different - it is called from Scala on the batch path, so
 * it has to be on the compile classpath, and putting it here is what keeps that boundary intact
 * (task 24, the owner's call). The price is the handful of bitmap helpers below, which are a
 * second copy of arithmetic the engine also owns; they are private and small, the layout they
 * implement is Arrow's and fixed, and {@link VarkaSelectionBitmap} in this package already keeps
 * a read-side copy for the same reason.
 *
 * <p>The scalar version this replaces walked the bitmap one row at a time and called Arrow's
 * per-value copy for each selected row. The vector version does one lane group at a time:
 * {@link IntVector#compress} moves the selected lanes to the low end of the vector -
 * {@code VPCOMPRESSD} on a machine with AVX-512, and a much slower emulation without one,
 * which is why this is measured at both vector widths before it is believed - and
 * {@link Long#compress} does the same for the validity bits, which is {@code PEXT} on x86-64.
 *
 * <p>Two things make this fast enough to be worth having, and both are load-bearing:
 *
 * <ul>
 *   <li><b>Every data store is unmasked.</b> A masked store costs 2.3x-2.9x
 *       ({@code SKILLS.md}), and this would pay one per lane group. The caller allocates the
 *       destination with one whole lane group of slack past the selected count, so a store at
 *       the running output position can always write a full vector: the lanes past the last
 *       selected row are overwritten by the next group, or land in the slack and are never
 *       read, because the vector's value count is set to the selected count afterwards.</li>
 *   <li><b>Nothing here is skipped for an empty group.</b> A group that selects no rows costs
 *       one bitmap read and a branch, which is the whole reason a low-selectivity filter is
 *       cheap.</li>
 * </ul>
 *
 * <p>The output's validity cannot be written a whole group at a time the way a kernel's can:
 * the compacted rows start at an arbitrary bit offset, so each group's bits are shifted into
 * place and ORed across the two or three bytes they span. The destination is zeroed first so
 * those ORs do not have to trust the allocator.
 */
public final class SelectionVectorOps {

  private static final VectorSpecies<Integer> SPECIES = IntVector.SPECIES_PREFERRED;
  private static final java.nio.ByteOrder ORDER = java.nio.ByteOrder.LITTLE_ENDIAN;

  private SelectionVectorOps() {}

  /**
   * The lane count of the int species this compaction runs at. The caller needs it to size the
   * destination with the slack the unmasked stores above depend on; it is a property of the
   * host, never a constant.
   */
  public static int intLanes() {
    return SPECIES.length();
  }

  /**
   * Copies the rows {@code selection} marks, in order, to the front of the destination.
   *
   * @param srcData address of the source int32 values ({@code len * 4} bytes).
   * @param srcValidity address of the source bit-packed validity; ignored (may be 0L) when
   *        {@code hasNulls} is false.
   * @param hasNulls whether the source has any null row.
   * @param selection the selection bitmap, bit set = row selected, at least
   *        {@code (len + 7) / 8} bytes.
   * @param len number of source rows.
   * @param dstData address of the destination int32 values.
   * @param dstDataBytes the destination data buffer's whole capacity, which must be at least
   *        {@code (selected + intLanes()) * 4} - see the class doc's unmasked-store note.
   * @param dstValidity address of the destination bit-packed validity.
   * @param dstValidityBytes the destination validity buffer's whole capacity.
   */
  public static void compactInts(
      long srcData, long srcValidity, boolean hasNulls, MemorySegment selection, int len,
      long dstData, long dstDataBytes, long dstValidity, long dstValidityBytes) {
    MemorySegment dstVal = segment(dstValidity, dstValidityBytes);
    // The per-group validity writes below OR into this, so it starts clean rather than
    // trusting the allocator to have zeroed it.
    dstVal.fill((byte) 0);
    if (len <= 0) {
      return;
    }
    MemorySegment src = segment(srcData, (long) len * 4);
    MemorySegment dst = segment(dstData, dstDataBytes);
    MemorySegment srcVal = hasNulls ? segment(srcValidity, (len + 7) / 8L) : null;

    int lanes = SPECIES.length();
    int loopBound = SPECIES.loopBound(len);
    int pos = 0;
    int i = 0;
    for (; i < loopBound; i += lanes) {
      long sel = bitsAt(selection, i, lanes) & lowBits(lanes);
      if (sel == 0) {
        continue;
      }
      VectorMask<Integer> m = VectorMask.fromLong(SPECIES, sel);
      // Unmasked load - the whole group is inside the batch - and an unmasked store into the
      // slack the caller allocated. compress leaves the selected lanes at the low end.
      IntVector.fromMemorySegment(SPECIES, src, (long) i * 4, ORDER)
          .compress(m).intoMemorySegment(dst, (long) pos * 4, ORDER);
      int selected = Long.bitCount(sel);
      long bits = hasNulls
          ? Long.compress(bitsAt(srcVal, i, lanes) & lowBits(lanes), sel)
          : lowBits(selected);
      orBitsAt(dstVal, pos, bits, selected);
      pos += selected;
    }
    // The final partial group, in its own method: it is the only place a masked load and the
    // partial bitmap read appear, and DateVectorOps records what leaving that shape inline in
    // a loop-bearing method costs.
    if (i < len) {
      compactEpilogue(src, dst, srcVal, hasNulls, selection, dstVal, i, len, pos);
    }
  }

  /** The fewer than {@code lanes} rows no whole group covered; see {@link #compactInts}. */
  private static void compactEpilogue(MemorySegment src, MemorySegment dst,
      MemorySegment srcVal, boolean hasNulls, MemorySegment selection, MemorySegment dstVal,
      int i, int len, int pos) {
    int rows = len - i;
    long sel = bitsAt(selection, i, rows);
    if (sel == 0) {
      return;
    }
    VectorMask<Integer> m = VectorMask.fromLong(SPECIES, sel);
    IntVector.fromMemorySegment(SPECIES, src, (long) i * 4, ORDER, SPECIES.indexInRange(i, len))
        .compress(m).intoMemorySegment(dst, (long) pos * 4, ORDER);
    int selected = Long.bitCount(sel);
    long bits = hasNulls
        ? Long.compress(bitsAt(srcVal, i, rows), sel)
        : lowBits(selected);
    orBitsAt(dstVal, pos, bits, selected);
  }

  // ---------------------------------------------------------------------------------------------
  // Bitmap arithmetic. A second copy of what VarkaVectorSupport owns for the engine's kernels -
  // see the class doc for why the module boundary forces it. Arrow's layout: LSB of byte 0 is
  // row 0, bit set = valid (or, for a selection bitmap, selected).
  // ---------------------------------------------------------------------------------------------

  /** A mask of the low {@code bits} bits. */
  private static long lowBits(int bits) {
    return bits >= 64 ? -1L : (1L << bits) - 1;
  }

  /** {@code addr} as a segment of {@code bytes} bytes - the only bounds check a kernel gets. */
  private static MemorySegment segment(long addr, long bytes) {
    return MemorySegment.ofAddress(addr).reinterpret(bytes);
  }

  /**
   * The {@code rows} validity bits starting at row {@code row}, lane 0 at bit 0. Reads only the
   * bytes those rows span, so it cannot run off a nominally sized bitmap, and {@code rows} is a
   * row count rather than a lane width - the whole-group form the engine uses derives its byte
   * span from a power-of-two width and cannot serve a partial group.
   */
  private static long bitsAt(MemorySegment bitmap, long row, int rows) {
    long byteOffset = row / 8;
    int shift = (int) (row % 8);
    int spanned = (shift + rows + 7) / 8;
    long bits = 0L;
    for (int b = 0; b < spanned; b++) {
      bits |= (bitmap.get(ValueLayout.JAVA_BYTE, byteOffset + b) & 0xFFL) << (b * 8);
    }
    return (bits >>> shift) & lowBits(rows);
  }

  /** ORs {@code rows} bits into the bitmap at row {@code row}; the inverse of {@link #bitsAt}. */
  private static void orBitsAt(MemorySegment bitmap, long row, long laneBits, int rows) {
    long byteOffset = row / 8;
    int shift = (int) (row % 8);
    long bits = (laneBits & lowBits(rows)) << shift;
    int spanned = (shift + rows + 7) / 8;
    for (int b = 0; b < spanned; b++) {
      long off = byteOffset + b;
      bitmap.set(ValueLayout.JAVA_BYTE, off,
          (byte) (bitmap.get(ValueLayout.JAVA_BYTE, off) | (byte) (bits >>> (b * 8))));
    }
  }
}
