/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.varka.execution;

import java.util.concurrent.ConcurrentHashMap;

/**
 * A single-owner class loader for generated bytecode (Varka Task 3).
 *
 * <p>The loader is the unit of unloading: generated bytecode is loaded into its own
 * {@link VarkaClassLoader}, and when the owner is done with it - originally at task end,
 * and since task 18 when catalyst's bounded shape cache evicts the entry - the owner
 * calls {@link #release()}, which clears the loader's own class registry, and drops its
 * references; once the loader becomes unreachable, the JVM unloads its classes and frees
 * Metaspace. That keeps Metaspace bounded by the owner's scope (a task, or a cache
 * capacity) where Spark's own codegen cache - bounded and size-evicting but never
 * releasing a loader - leaves retention bounded only by churn.
 *
 * <p>The registry + {@link #findClass(String)} mirror Spark's
 * {@code InMemoryClassLoader} (CodeCompiler.scala), so callers can use
 * {@code loadClass(name)} after {@link #defineGeneratedClass(String, byte[])}.
 *
 * <p>Catalyst carries an identical copy, {@code VarkaGeneratedClassLoader}, which is the one
 * the live execution path uses. The duplication is deliberate, not an oversight waiting to be
 * deduplicated: neither module can depend on the other. This module is standalone, outside the
 * Spark reactor, a test-scope dependency of catalyst and deployed externally at runtime, so
 * catalyst cannot compile against it; and it cannot depend on catalyst either. The two are kept
 * deliberately identical in behaviour, and a change to one belongs in the other. This copy is
 * what {@code VarkaClassLoaderTest} pins - including the Metaspace-unload proof - and what
 * {@code DateVectorOpsEmissionTest} loads its probe class through.
 */
public final class VarkaClassLoader extends ClassLoader {

  private final ConcurrentHashMap<String, Class<?>> definedClasses = new ConcurrentHashMap<>();

  private volatile boolean released;

  public VarkaClassLoader(ClassLoader parent) {
    super(parent);
  }

  /**
   * Defines a generated class and registers it so {@code loadClass(name)} resolves it.
   *
   * @param className the binary name of the class; must match the class in {@code bytes}.
   * @param bytes the class file bytes.
   * @return the defined {@link Class}.
   * @throws IllegalStateException if {@link #release()} has already been called.
   */
  public Class<?> defineGeneratedClass(String className, byte[] bytes) {
    if (released) {
      throw new IllegalStateException("VarkaClassLoader has already been released");
    }
    Class<?> clazz = defineClass(className, bytes, 0, bytes.length);
    definedClasses.put(className, clazz);
    return clazz;
  }

  /**
   * Marks the loader released and clears the class registry so the loader no longer
   * retains its generated classes. Idempotent and thread-safe.
   *
   * <p>This is only half of the unload contract: the owner (the Spark task) must also
   * drop its references to the generated classes and instances. Only then does the
   * loader become unreachable and its classes unload from Metaspace.
   */
  public void release() {
    released = true;
    definedClasses.clear();
  }

  public boolean isReleased() {
    return released;
  }

  @Override
  protected Class<?> findClass(String name) throws ClassNotFoundException {
    Class<?> clazz = definedClasses.get(name);
    if (clazz != null) {
      return clazz;
    }
    throw new ClassNotFoundException(name);
  }
}
