/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.catalyst.expressions.codegen;

import java.util.concurrent.ConcurrentHashMap;

/**
 * A single-owner class loader for Varka Class-File generated bytecode, mirroring the engine
 * module's {@code org.apache.spark.sql.varka.execution.VarkaClassLoader} so the two sides of
 * the MVP share the same unload contract: the owner - a task before task 18, an entry of the
 * bounded {@code VarkaShapeCache} since - calls {@link #release()} when it is done and drops
 * its references, and the JVM unloads the loader's classes from Metaspace. The registry +
 * {@link #findClass(String)} mirror Spark's {@code InMemoryClassLoader} (CodeCompiler.scala),
 * so callers can use {@code loadClass(name)} after
 * {@link #defineGeneratedClass(String, byte[])}.
 *
 * <p>The duplication with the engine's copy is deliberate, not an oversight waiting to be
 * deduplicated: neither module can depend on the other. The engine is only a test-scope
 * dependency here and at runtime is deployed externally ({@code --jars}) - so catalyst cannot
 * compile against it - while the engine in turn cannot depend on catalyst. The two classes are
 * therefore kept deliberately identical in behaviour, and a change to one belongs in the other.
 *
 * <p>Task 23 ported this class from Scala, which makes that identity literal rather than merely
 * behavioural: the two bodies now differ only in class name and package. The Scala original was
 * declared {@code private[sql]}; Java has no equivalent, so the class is plain public. That
 * widens nothing in practice - {@code private[sql]} is already public in bytecode, and the only
 * callers are {@code VarkaShapeCache} and Varka's own suites and benchmarks.
 */
public final class VarkaGeneratedClassLoader extends ClassLoader {

  private final ConcurrentHashMap<String, Class<?>> definedClasses = new ConcurrentHashMap<>();

  private volatile boolean released;

  public VarkaGeneratedClassLoader(ClassLoader parent) {
    super(parent);
  }

  /**
   * Defines a generated class and registers it so {@code loadClass(name)} resolves it.
   *
   * @param className the binary name of the class; must match the class in {@code bytes}.
   * @param bytes the class file bytes.
   * @return the defined {@link Class}.
   * @throws IllegalStateException if {@link #release()} has already been called.
   */
  public Class<?> defineGeneratedClass(String className, byte[] bytes) {
    if (released) {
      throw new IllegalStateException("VarkaGeneratedClassLoader has already been released");
    }
    Class<?> clazz = defineClass(className, bytes, 0, bytes.length);
    definedClasses.put(className, clazz);
    return clazz;
  }

  /**
   * Marks the loader released and clears the class registry so the loader no longer retains
   * its generated classes. Idempotent and thread-safe.
   *
   * <p>This is only half of the unload contract: the owner - the shape-cache entry since task
   * 18 - must also drop its references to the generated classes and instances. Only then does
   * the loader become unreachable and its classes unload from Metaspace.
   */
  public void release() {
    released = true;
    definedClasses.clear();
  }

  public boolean isReleased() {
    return released;
  }

  @Override
  protected Class<?> findClass(String name) throws ClassNotFoundException {
    Class<?> clazz = definedClasses.get(name);
    if (clazz != null) {
      return clazz;
    }
    throw new ClassNotFoundException(name);
  }
}
