/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.catalyst.expressions.codegen.varka

import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.security.MessageDigest

import scala.jdk.CollectionConverters._
import scala.util.Random

import com.fasterxml.jackson.databind.ObjectMapper

import org.apache.spark.SparkFunSuite
import org.apache.spark.sql.catalyst.expressions.{Alias, Attribute, AttributeReference, Expression}
import org.apache.spark.sql.catalyst.expressions.codegen.VarkaExpressionCompiler
import org.apache.spark.sql.catalyst.expressions.codegen.varka.VarkaIrGrammar._
import org.apache.spark.sql.catalyst.parser.CatalystSqlParser
import org.apache.spark.sql.types.{DateType, IntegerType, YearMonthIntervalType}

/**
 * The emitted-bytes oracle (task 85, step 1): what the emitter produces for every int32 shape,
 * pinned so that a refactor of the emitter can prove it changed nothing.
 *
 * Two shape sets. Every row of the coverage table (`sql/varka/coverage.json`, compiled to IR
 * the way `VarkaCoverageSuite` compiles it), and ten thousand random trees from the shared
 * fuzz grammar at a fixed seed. Each shape is emitted at two lane counts - `lanesOverride` 4
 * and 16, which are 128 and 512 bits at the int lane - and every method body of the emitted
 * class is rendered symbolically (`VarkaEmitterTestSupport.methodBodies`: opcodes and resolved
 * operands, labels numbered, no constant-pool indices and no line tables) and hashed.
 *
 * What `sql/varka/emitted_bytes.json` pins: for each width, one hash per method per coverage
 * row, so a difference on a named shape says which method moved; and, for the fuzz sequence,
 * one digest per block of a hundred shapes, so a difference names the block and the suite can
 * re-emit that block to find the shape. The committed file is generated by this suite and
 * compared byte for byte, on `VarkaCoverageSuite`'s precedent:
 *
 * {{{
 *   VARKA_BYTES_REGEN=true build/sbt 'catalyst/testOnly *VarkaEmittedBytesSuite'
 * }}}
 *
 * A difference is a change in what an emitted method does. It is not always a bug - a task
 * that means to change the emitted code regenerates the file and says so in its plan - but it
 * is never a note: the step that produced it reads the two renderings before it is accepted.
 */
class VarkaEmittedBytesSuite extends SparkFunSuite {

  private val seed = 20260916L
  private val shapes = 10000
  private val blockSize = 100
  private val widths = Seq(4, 16)

  // The coverage table's columns, as `VarkaCoverageSuite` declares them.
  private val d = AttributeReference("d", DateType)()
  private val d2 = AttributeReference("d2", DateType)()
  private val i = AttributeReference("i", IntegerType)()
  private val ymm = AttributeReference("ymm",
    YearMonthIntervalType(YearMonthIntervalType.MONTH, YearMonthIntervalType.MONTH))()
  private val ymy = AttributeReference("ymy",
    YearMonthIntervalType(YearMonthIntervalType.YEAR, YearMonthIntervalType.YEAR))()
  private val ym = AttributeReference("ym",
    YearMonthIntervalType(YearMonthIntervalType.YEAR, YearMonthIntervalType.MONTH))()
  private val columns: Seq[Attribute] = Seq(d, d2, i, ymm, ymy, ym)

  private val className = "org.apache.spark.sql.varka.execution.VarkaEmittedBytesOracle"

  private def sha(text: String): String = {
    val digest = MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8))
    digest.take(8).map(b => f"$b%02x").mkString
  }

  /** Method name and descriptor to the hash of its rendered body, in declaration order. */
  private def methodHashes(roots: Seq[VarkaVectorIR], numInputs: Int, numLiterals: Int,
      lanes: Int): Seq[(String, String)] = {
    val options = VarkaEmitOptions.DEFAULTS.withLanesOverride(lanes)
    val bytes = VarkaLoopEmitter.emit(className, roots.asJava, numInputs, numLiterals, null, null,
      options)
    VarkaEmitterTestSupport.methodBodies(bytes).asScala.toSeq.map { case (m, body) =>
      m -> sha(body)
    }
  }

  // ---------------------------------------------------------------------------------------
  // The coverage rows
  // ---------------------------------------------------------------------------------------

  private case class CoverageShape(sql: String, roots: Seq[VarkaVectorIR], numInputs: Int,
      numLiterals: Int)

  /**
   * Every row of the table as IR, through the compiler: a projection row's compiled outputs, a
   * predicate row's fused condition root. A row whose SQL does not parse - the `InSet` caption,
   * until the table carries an executable spelling for it - is recorded as skipped, by name, so
   * the file says what it does not pin.
   */
  private lazy val coverage: (Seq[CoverageShape], Seq[String]) = {
    val file = getWorkspaceFilePath("sql", "varka", "coverage.json").toFile
    val doc = new ObjectMapper().readTree(file)
    val shapes = Seq.newBuilder[CoverageShape]
    val skipped = Seq.newBuilder[String]
    doc.get("expressions").elements().asScala.foreach { e =>
      val sql = e.get("sql").asText()
      val executable = Option(e.get("executable")).map(_.asText()).getOrElse(sql)
      val form = e.get("form").asText()
      val resolved: Option[Expression] =
        try Some(VarkaSqlResolve.resolve(CatalystSqlParser.parseExpression(executable), columns))
        catch { case _: Exception => None }
      val compiled = resolved.flatMap { expr =>
        if (form == "predicate") {
          VarkaExpressionCompiler.compilePredicate(expr, columns).map(_.fused)
        } else {
          VarkaExpressionCompiler.compile(Seq(Alias(expr, "c")()), columns)
        }
      }
      compiled match {
        case Some(c) =>
          shapes += CoverageShape(sql, c.outputs, c.inputOrdinals.size, c.literals.size)
        case None => skipped += sql
      }
    }
    (shapes.result(), skipped.result())
  }

  // ---------------------------------------------------------------------------------------
  // The fuzz sequence
  // ---------------------------------------------------------------------------------------

  private case class FuzzShape(roots: Seq[VarkaVectorIR], numInputs: Int, numLiterals: Int)

  /** Shape `k` of the sequence, drawn the way `VarkaIrFuzzSuite.runOne` draws its trees. */
  private def fuzzShape(k: Int): FuzzShape = {
    val rnd = new Random(seed * 1000003L + k)
    val numInputs = 1 + rnd.nextInt(3)
    val numLiterals = rnd.nextInt(3)
    val smallOrdinal = if (numInputs > 1) numInputs - 1 else -1
    val levelOrdinal = if (numInputs > 2) numInputs - 2 else -1
    val grammar = new Shapes(rnd, numInputs, numLiterals, smallOrdinal, levelOrdinal)
    val depth = 1 + rnd.nextInt(4)
    val roots: Seq[VarkaVectorIR] =
      if (rnd.nextInt(5) == 0) Seq(grammar.cond(depth))
      else Seq.fill(1 + rnd.nextInt(3))(grammar.value(depth).node).distinct
    FuzzShape(roots, numInputs, numLiterals)
  }

  /** The digest of one block of the sequence at one width. */
  private def blockDigest(block: Int, lanes: Int): String = {
    val sb = new StringBuilder
    for (k <- block * blockSize until math.min((block + 1) * blockSize, shapes)) {
      val s = fuzzShape(k)
      sb.append(k).append(':')
      methodHashes(s.roots, s.numInputs, s.numLiterals, lanes).foreach { case (m, h) =>
        sb.append(' ').append(m).append('=').append(h)
      }
      sb.append('\n')
    }
    sha(sb.toString)
  }

  // ---------------------------------------------------------------------------------------
  // The file
  // ---------------------------------------------------------------------------------------

  private def render(): String = {
    def ordered(pairs: (String, Any)*): java.util.LinkedHashMap[String, Any] = {
      val map = new java.util.LinkedHashMap[String, Any]()
      pairs.foreach { case (k, v) => map.put(k, v) }
      map
    }
    val (rows, skipped) = coverage
    val perWidth = widths.map { lanes =>
      val coverageHashes = ordered(rows.map { r =>
        r.sql -> ordered(methodHashes(r.roots, r.numInputs, r.numLiterals, lanes): _*)
      }: _*)
      val blocks = (0 until (shapes + blockSize - 1) / blockSize).map(blockDigest(_, lanes))
      lanes.toString -> ordered(
        "coverage" -> coverageHashes,
        "fuzz" -> ordered(
          "seed" -> seed, "shapes" -> shapes, "block_size" -> blockSize,
          "blocks" -> blocks.asJava))
    }
    val doc = ordered(
      "generated_by" -> ("VarkaEmittedBytesSuite; regenerate with VARKA_BYTES_REGEN=true " +
        "build/sbt 'catalyst/testOnly *VarkaEmittedBytesSuite'"),
      "description" -> ("Hashes of every emitted method body, rendered symbolically, for every " +
        "coverage row and for a fixed sequence of fuzz shapes, at lanesOverride 4 and 16. A " +
        "difference is a change in what an emitted method does."),
      "coverage_rows_skipped" -> skipped.asJava,
      "lanes" -> ordered(perWidth: _*))
    new ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(doc) + "\n"
  }

  private def regenerate: Boolean = sys.env.get("VARKA_BYTES_REGEN").contains("true")

  test("sql/varka/emitted_bytes.json pins what the emitter produces for every int32 shape") {
    val path = getWorkspaceFilePath("sql", "varka", "emitted_bytes.json")
    val rendered = render()
    if (regenerate) {
      Files.write(path, rendered.getBytes(StandardCharsets.UTF_8))
      logInfo(s"regenerated $path")
    } else {
      assert(Files.exists(path), s"$path is missing; generate it with\n" +
        "  VARKA_BYTES_REGEN=true build/sbt 'catalyst/testOnly *VarkaEmittedBytesSuite'")
      val committed = new String(Files.readAllBytes(path), StandardCharsets.UTF_8)
      if (committed != rendered) {
        // Name what moved before failing: the coverage rows and methods whose hash differs,
        // and the fuzz blocks, so the reader goes straight to a shape.
        val mapper = new ObjectMapper()
        val before = mapper.readTree(committed)
        val after = mapper.readTree(rendered)
        val moved = Seq.newBuilder[String]
        widths.foreach { lanes =>
          val b = before.get("lanes").get(lanes.toString)
          val a = after.get("lanes").get(lanes.toString)
          if (b == null) {
            moved += s"lanes $lanes: no committed entry"
          } else {
            a.get("coverage").fields().asScala.foreach { entry =>
              val was = b.get("coverage").get(entry.getKey)
              if (was == null) moved += s"lanes $lanes: new row ${entry.getKey}"
              else entry.getValue.fields().asScala.foreach { m =>
                val old = was.get(m.getKey)
                if (old == null || old.asText() != m.getValue.asText()) {
                  moved += s"lanes $lanes: ${entry.getKey} method ${m.getKey}"
                }
              }
            }
            val bb = b.get("fuzz").get("blocks")
            a.get("fuzz").get("blocks").elements().asScala.zipWithIndex.foreach { case (n, k) =>
              if (bb == null || bb.size <= k || bb.get(k).asText() != n.asText()) {
                moved += s"lanes $lanes: fuzz block $k (shapes ${k * blockSize} to " +
                  s"${(k + 1) * blockSize - 1})"
              }
            }
          }
        }
        fail("sql/varka/emitted_bytes.json does not match what the emitter produces. If the " +
          "emitted code was meant to change, regenerate with\n" +
          "  VARKA_BYTES_REGEN=true build/sbt 'catalyst/testOnly *VarkaEmittedBytesSuite'\n" +
          "and say so in the task's plan. What moved:\n  " + moved.result().mkString("\n  "))
      }
    }
  }

  test("the two widths differ where the lane count is baked in, so the oracle sees width") {
    // A single shape emitted at 4 and 16 lanes must render differently somewhere: the species
    // constant is baked into the class, and a width that left every method identical would
    // mean the override was ignored and the second width pins nothing.
    val (rows, _) = coverage
    assert(rows.nonEmpty)
    val r = rows.head
    val at4 = methodHashes(r.roots, r.numInputs, r.numLiterals, 4).toMap
    val at16 = methodHashes(r.roots, r.numInputs, r.numLiterals, 16).toMap
    assert(at4 != at16, s"${r.sql}: identical at 4 and 16 lanes")
  }
}
